### ISSUE TITLE
 11 and 12 column meaning 

### ISSUE THREAD

**Issue by yancychy** [stephenfloor/extract-transcript-regions#3]
Hi,
  How to understand the 11 and 12 column? 
   As shown in the example, how to identify the 3 utr length from the last columns? Thanks very much. 

chr3 108107279 108109424 ENSMUST00000000001.4_3utr  0  - 108107279 108109424  0   2 
2037,22,    0,2123, 

Best regards,
Yang Chen

**Comment by stephenfloor** [comment]
Hi, 
The output is in block BED format, as described here: https://genome.ucsc.edu/FAQ/FAQformat.html#format1

Briefly, the 10th column says how many regions there are, the 11th column is how large the blocks are, and the 12th column is the starts for the blocks. So the line you included would be a two block 3' UTR (two exons) with one starting at position 0 of length 2037 and the second starting at position 2123 with length 22, or total length 2059. The positions are offset from the chromStart (column 2).

Hope that helps,
Stephen

**Comment by yancychy** [comment]
Thanks Stephen. It's much helpful.
