### ISSUE TITLE
error in running 'extract_transcript_regions.py'

### ISSUE THREAD

**Issue by qicaibiology** [stephenfloor/extract-transcript-regions#4]
I am running it under anaconda3 ; the error is like following:
```
File "extract_transcript_regions.py", line 6
    <!DOCTYPE html>
    ^
SyntaxError: invalid syntax
```

How can I make it work?

**Comment by stephenfloor** [comment]
Sounds like it may be downloaded as html instead of saved as a python file. Perhaps the webpage with the file on it was saved instead of the file directly? Try downloading the file in a different way - if you do "head" on the file in terminal to see the top of it that should look the same as the start of the file viewed on github if it's downloaded in the correct format.

**Comment by qicaibiology** [comment]
> Sounds like it may be downloaded as html instead of saved as a python file. Perhaps the webpage with the file on it was saved instead of the file directly? Try downloading the file in a different way - if you do "head" on the file in terminal to see the top of it that should look the same as the start of the file viewed on github if it's downloaded in the correct format.

I re-do as you advised:
```
the error is:File "extract_transcript_regions.py", line 15
    print " ----------------------------------"
                                              ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(" ----------------------------------")?
```
It looks that I need to use python2. However, I am currently running under Anaconda3. Do you know how to activate python2 enviroment for this ?

Thanks,

**Comment by stephenfloor** [comment]
Glad that the download worked! There are tutorials online for enabling python2 in Anaconda3 that I will ask that you please read. I am not able to support that. Good luck.

**Comment by qicaibiology** [comment]
> nabling python2 in Anaco

Thanks for telling me this. Very much appreciated!

**Comment by qicaibiology** [comment]
> Glad that the download worked! There are tutorials online for enabling python2 in Anaconda3 that I will ask that you please read. I am not able to support that. Good luck.

I have a new problem Traceback (most recent call last):
  ```
File "extract_transcript_regions.py", line 9, in <module>
    import GTF
ImportError: No module named GTF
```
I searched a while for installing GTF but did not get the answer that fit its name? I found gffuntil or gtfparese. What is GTF module and how can i get it?

**Comment by saketkc** [comment]
I am not sure if you have done any additional changes to the script. The error seems to be arising because `region` is an OrderedDict, not a `gffutils` feature object as it should be.
